CREATE TABLE Users (
    User_ID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Contact_Info VARCHAR2(20),
    Role VARCHAR2(20)
);

CREATE TABLE Vehicles (
    Vehicle_ID NUMBER PRIMARY KEY,
    Owner_ID NUMBER REFERENCES Users(User_ID),
    License_Plate VARCHAR2(20),
    Type VARCHAR2(20)
);

CREATE TABLE Parking_Slots (
    Slot_ID NUMBER PRIMARY KEY,
    Status VARCHAR2(20),
    Vehicle_Assigned NUMBER UNIQUE
);

CREATE TABLE Transactions (
    Transaction_ID NUMBER PRIMARY KEY,
    Vehicle_ID NUMBER REFERENCES Vehicles(Vehicle_ID),
    Entry_Time TIMESTAMP,
    Exit_Time TIMESTAMP,
    Payment_Status VARCHAR2(20)
);

CREATE TABLE Attendants (
    Employee_ID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Shift VARCHAR2(20),
    Assigned_Area VARCHAR2(50)
);

CREATE TABLE Public_Holidays (
    Holiday_Date DATE PRIMARY KEY
);

CREATE TABLE audit_log (
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Table_Name VARCHAR2(100),
    Operation VARCHAR2(10),
    Changed_By VARCHAR2(100),
    Change_Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Old_Value CLOB,
    New_Value CLOB
);